from babel.messages.pofile import read_po, write_po

with open('app/translations/fr/LC_MESSAGES/messages.po', 'rb') as f:
    catalog = read_po(f)

translations = {
    "QCM Platform": "Plateforme QCM",
    "Role:": "Rôle :",
    "Admin Panel": "Panneau d'administration",
    "User Panel": "Panneau utilisateur",
    "Dashboard": "Tableau de bord",
    "Logout": "Déconnexion",
    "Sign In": "Se connecter",
    "Title": "Titre",
    "Message": "Message",
    "Cancel": "Annuler",
    "Confirm": "Confirmer",
    "Attention": "Attention",
    "Please enter a value.": "Veuillez saisir une valeur.",
    "Yes": "Oui",
    "Login": "Connexion",
    "Username": "Nom d'utilisateur",
    "Password": "Mot de passe",
    "Don't have an account?": "Vous n'avez pas de compte ?",
    "Register\n                    here": "S'inscrire\n                    ici",
    "Register - QCM Platform": "Inscription - Plateforme QCM",
    "Student Registration": "Inscription Étudiant",
    "Confirm Password": "Confirmer le mot de passe",
    "Register": "S'inscrire",
    "Already have an account?": "Vous avez déjà un compte ?",
    "Login here": "Connectez-vous ici",
    "Student Dashboard": "Tableau de bord Étudiant",
    "Join a Quiz": "Rejoindre un QCM",
    "Enter an access code to start a quiz directly.": "Entrez un code d'accès pour commencer un QCM directement.",
    "e.g. AB12CD34": "ex. AB12CD34",
    "Join": "Rejoindre",
    "Join a Classroom": "Rejoindre une Classe",
    "Enter a class code provided by your teacher.": "Entrez un code de classe fourni par votre professeur.",
    "e.g. XY9Z": "ex. XY9Z",
    "Enroll": "S'inscrire",
    "Live Session": "Session en Direct",
    "Enter a 4-digit game PIN to join.": "Entrez un PIN à 4 chiffres pour rejoindre.",
    "PIN": "PIN",
    "Your Stats": "Vos Statistiques",
    "Attempts": "Tentatives",
    "Avg Score": "Score Moyen",
    "Total XP": "XP Total",
    "Day Streak": "Série de jours",
    "Competency Radar": "Radar de Compétences",
    "Take more categorized quizzes\n                to\n                see your competency radar.": "Répondez à plus de QCM catégorisés\n                pour\n                voir votre radar de compétences.",
    "🏆 Your Trophy Case": "🏆 Votre Vitrine des Trophées",
    "You haven't\n        earned any\n        badges yet. Keep taking quizzes to unlock them!": "Vous n'avez\n        pas encore gagné\n        de badges. Continuez à répondre aux QCM pour les débloquer !",
    "Pending Assignments": "Devoirs en Attente",
    "Class:": "Classe :",
    "Practice": "S'entraîner",
    "Take Quiz": "Faire le QCM",
    "No pending assignments from your\n        classrooms.": "Aucun devoir assigné dans vos\n        classes.",
    "Your Enrolled Classrooms": "Salles de Classes Inscrites",
    "Teacher:": "Professeur :",
    "Code:": "Code :",
    "You haven't joined any classrooms\n        yet.": "Vous n'avez pas encore rejoint de classe.",
    "Past Submissions": "Soumissions Passées",
    "Quiz Title": "Titre du QCM",
    "Date Taken": "Date",
    "Score": "Score",
    "You haven't taken any quizzes\n        yet.": "Vous n'avez pas encore passé de QCM.",
    "Competency (%)": "Compétence (%)",
    "'s Dashboard": " - Tableau de bord",
    "Import\n            CSV": "Importer\n            CSV",
    "Classrooms": "Classes",
    "Question Bank": "Banque de Questions",
    "Create New Quiz": "Créer un QCM",
    "Active QCMs": "QCM Actifs",
    "Total Student Returns": "Retours d'Étudiants",
    "At-Risk Students": "Étudiants en Difficulté",
    "Attention Required: At-Risk Students": "Attention Requise : Étudiants en Difficulté",
    "Students averaging below 50%\n        across\n        your assessments.": "Étudiants ayant une moyenne inférieure à 50%\n        sur\n        vos évaluations.",
    "Student": "Étudiant",
    "Average Score": "Score Moyen",
    "Total Attempts": "Tentatives",
    "Search by title or code...": "Rechercher par titre ou code...",
    "Search": "Rechercher",
    "Clear": "Effacer",
    "s limit": "s limite",
    "Qs": "Q",
    "runs": "participations",
    "Host\n                    Live": "Lancer\n                    Live",
    "Results": "Résultats",
    "Edit": "Modifier",
    "Delete": "Supprimer",
    "No quizzes found": "Aucun QCM trouvé",
    "This account hasn't created any quizzes yet.": "Ce compte n'a pas encore créé de QCM.",
    "Create First Quiz": "Créer le premier QCM",
    "Prev": "Prédédent",
    "Next": "Suivant",
    "Delete Quiz": "Supprimer le QCM",
    "Are you sure you want to delete this quiz? This action cannot be undone.": "Êtes-vous sûr de vouloir supprimer ce QCM ? Cette action est irréversible."
}

for message in catalog:
    if message.id in translations:
        message.string = translations[message.id]

with open('app/translations/fr/LC_MESSAGES/messages.po', 'wb') as f:
    write_po(f, catalog)
print("Translations applied successfully.")
