"""change username to email and add confirmation

Revision ID: 70dbf20a3a62
Revises: 8d4a5a6a8b89
Create Date: 2026-03-03 19:48:26.973563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70dbf20a3a62'
down_revision = '8d4a5a6a8b89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # 1. Add column as nullable first
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('email_confirmed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('confirmation_code', sa.String(length=6), nullable=True))
        
    # 2. Populate existing rows to satisfy constraints
    op.execute("UPDATE user SET email = username || '@qcm.com' WHERE email IS NULL")
    op.execute("UPDATE user SET email_confirmed = 1 WHERE email_confirmed IS NULL")

    with op.batch_alter_table('user', schema=None) as batch_op:
        # 3. Alter columns to be NOT NULL
        batch_op.alter_column('email', existing_type=sa.String(length=120), nullable=False)
        batch_op.alter_column('email_confirmed', existing_type=sa.Boolean(), nullable=False)
        
        # 4. Handle constraints and drop old column
        batch_op.drop_constraint('uq_user_username', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=80), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])
        batch_op.drop_column('confirmation_code')
        batch_op.drop_column('email_confirmed')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
