"""Added deleted_by_sender and deleted_by_receiver to Message

Revision ID: 8d4a5a6a8b89
Revises: 6e8572bdd5fb
Create Date: 2026-03-02 20:46:43.485128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d4a5a6a8b89'
down_revision = '6e8572bdd5fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_by_sender', sa.Boolean(), server_default='0', nullable=True))
        batch_op.add_column(sa.Column('deleted_by_receiver', sa.Boolean(), server_default='0', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('deleted_by_receiver')
        batch_op.drop_column('deleted_by_sender')

    # ### end Alembic commands ###
